before:
  hooks:
    - pkger -include /payloads -o ./cmd

builds:
  - goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    flags:
      - -trimpath

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: x64
      darwin: macOS
    wrap_in_directory: false
    format: zip
    format_overrides:
      - goos: linux
        format: tar.gz
    files:
      - LICENSE
      - README.md

nfpms:
  - package_name: govenom
    vendor: Erik Geiser
    homepage: https://github.com/erikgeiser/govenom
    maintainer: Erik Geiser <erik.geiser@posteo.net>
    description: Govenom is a msfvenom-inspired cross-platform payload generator toolkit
    license: MIT
    formats:
      - deb
      - rpm
    dependencies:
      - golang
    overrides:
      rpm:
        replacements:
          amd64: x32_64

checksum:
  name_template: 'checksums.txt'

changelog:
  filters:
    exclude:
      - Merge
