name: Build
on: [push]
jobs:
  linux-builds:
    name: "linux build"
    runs-on: ubuntu-latest
    steps:
      - name: "Set up Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
        id: go

      - name: "Check out code"
        uses: actions/checkout@v1

      - name: "prepare build"
        run: |
          go get -u github.com/markbates/pkger/cmd/pkger
          pkger -include /payloads -o ./cmd
          rm -rf payloads

      - name: "build govenom"
        run: |
          go build

      - name: "build rsh"
        run: |
          ./govenom payload rsh -d 127.0.0.1:1234 -o rsh

      - name: "build xrsh"
        run: |
          ./govenom payload xrsh -d 127.0.0.1:1234 -o xrsh

      - name: "build stager"
        run: |
          GOOS=windows ./govenom payload stager -d 127.0.0.1:1234 -o stager.exe

      - name: "check file existence"
        uses: andstor/file-existence-action@v1
        with:
          files: "rsh, xrsh, stager.exe"

  windows:
    name: "windows build"
    runs-on: windows-latest
    steps:
      - name: "set up go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x
        id: go

      - name: "check out code"
        uses: actions/checkout@v1

      - name: "prepare build"
        run: |
          go get -u github.com/markbates/pkger/cmd/pkger
          pkger -include /payloads -o ./cmd
          rm -R .\payloads

      - name: "build govenom"
        run: |
          go build

      - name: "build rsh"
        run: |
          ./govenom payload rsh -d 127.0.0.1:1234 -o rsh.exe

      - name: "build xrsh"
        run: |
          ./govenom payload xrsh -d 127.0.0.1:1234 -o xrsh.exe

      - name: "build stager"
        run: |
          ./govenom payload stager -d 127.0.0.1:1234 -o stager.exe

      - name: "check file existence"
        uses: andstor/file-existence-action@v1
        with:
          files: "rsh.exe, xrsh.exe, stager.exe"
